[package]
edition = "2021"
name = "da14531-sdk"
version = "0.1.0"

[dependencies]
cty = "0.2.2"
paste = "1.0.7"
rtt-target = "0.3.1"

[build-dependencies]
bindgen = "0.59.2"
lazy_static = "1.4.0"

[features]
default = ["ble_custom_server1"]

ble_custom_server1 = []
ble_custom_server2 = []
